Update Release 3 notes
SovereignCloudStack/Docs pull request #107
Opened 2022-09-07 15:28 UTC by osfrickler

Add some more OSISM related details and cleanup some minor issues.

Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>

2022-09-07 18:24 UTC, berendt approved these changes

2022-09-07 19:11 UTC, fkr commented on Release-Notes/Release3.md
> +* Distributed Virtual Routing (DVR) is not officially supported by us, not tested and not recommended.
I would not use the phrase "supported by us" - but instead "supported by OSISM".
I actually had the same thought, when I read that change in the OSISM's changelog and wanted to suggest the same wording there.

2022-09-07 19:15 UTC, fkr commented on Release-Notes/Release3.md
> +  therefore we will remove the ``hddtemp`` service in the next release, as there is
I'd suggest a different wording:

"If Linux bridge is used in deployments, migrating to OpenVSwitch is recommended".

For the hddtemp comment:

"therefore ``hddtemp`` will be removed from the next OSISM release"

2022-09-07 19:15 UTC, fkr requested changes
see comments.

2022-09-07 19:15 UTC, fkr commented
thanks @osfrickler - really good additions, I made a few small comments regarding some wording.

2022-09-08 09:15 UTC, fkr approved these changes
LGTM!

2022-09-08 09:16 UTC, fkr commented
thanks @osfrickler

2022-09-08 09:16 UTC, merged