Add artcodix as compliant cloud.
SovereignCloudStack/docs pull request #128
Opened 2023-12-21 21:41 UTC by garloff

Also list artcodix CNDS cloud on docs page.

2023-12-21 21:53 UTC, berendt requested changes

2023-12-21 21:53 UTC, berendt commented on standards/certification/certified-clouds.md
> +| [REGIO.cloud](https://regio.digital)                                                                           | Public cloud for customers                        | OSISM GmbH                    |
While touching this please replace Dashboard with HM in the REGIO.cloud row.

2024-01-25 13:29 UTC, maxwolfs approved these changes

2024-01-25 13:52 UTC, berendt approved these changes

2024-01-25 13:53 UTC, merged