Document federated users role limitation #360
SovereignCloudStack/docs pull request #138
Opened 2024-02-02 16:06 UTC by JuanPTM

Add role limitation explanatiion to docs

2024-02-02 19:06 UTC, reqa commented on docs/05-iam/index.md
> +  the `epehemeral` users roles are not clean up.
```suggestion
- Keystone currently has another limitation. This is limitation is also being addressed by the SCS development team aligned
  with upstream OpenDev development plans. The roles for federated users are stored on the database for the `ephemeral` users 
  created during a federated login. This also limits the ability to modify users roles from the identity source directly, as roles of
  the `epehemeral` users do not get cleaned up or updated based on changes in the claims contained in the  OpenID-Connect token.
```

2024-02-21 11:17 UTC, reqa requested changes

2024-02-21 11:17 UTC, reqa commented on docs/05-iam/index.md
> +  the `epehemeral` users do not get cleaned up or updated based on changes in the claims contained in the  OpenID-Connect token.
```suggestion
- Keystone currently has another limitation which is being addressed by the SCS development team aligned
  with upstream OpenDev development plans: The roles for federated users are stored on the database for the `ephemeral` users 
  created during a federated login. This limits the ability to modify users roles from the identity source directly, as roles of
  the `epehemeral` users do not get cleaned up or updated based on changes in the claims contained in the  OpenID-Connect token.
```

2024-02-21 11:25 UTC, bitkeks commented
LGTM!

Regarding the limitations that are *being addressed by the SCS development team aligned with upstream OpenDev development plans* - are there links to discussions or gerrit?

2024-02-22 09:51 UTC, reqa approved these changes

2024-02-23 11:51 UTC, merged