Create How to guide for security groups
SovereignCloudStack/docs pull request #142
Opened 2024-02-19 14:56 UTC by josephineSei

Instead of a standard, the security groups just allow a guide for best practice including basic recommended security groups.

This is part of the ticket: https://github.com/SovereignCloudStack/standards/issues/473

2024-03-07 21:09 UTC, markus-hentsch requested changes

2024-03-07 21:10 UTC, markus-hentsch commented
Did a first review, see review comments.

Things I didn't address yet:

1. We should add a warning section/banner early in the document stating that security groups can be edited at runtime *affecting all ports/VMs they are assigned to immediately*. SCS should make users aware of this as I think this is a very important detail that may not be immediately obvious.
2. In many paragraphs "Ports" is written with a capital "P", most likely to differentiate Neutron Ports from actual network ports (numbers or NICs). However, in contrast "security groups" is using lower case across the document but also refers to a special concept of OpenStack not identical to the linguistic interpretation of the word combination "security groups".
3. I'm wondering if we should recommend using security groups as a grouping feature primarily. I.e. not creating individual groups for HTTP, HTTPS, ICMP etc. but actually bringing the "groups" concept into play by suggesting creating abstract service groups, for example:
    - admin group: ICMP, SSH port
    - webserver group: HTTP, HTTPS ports
    - infrastructure group: NTP, DNS ports

2024-03-08 07:00 UTC, josephineSei commented
> Did a first review, see review comments.
> 
> Things I didn't address yet:
> 
>     1. We should add a warning section/banner early in the document stating that security groups can be edited at runtime _affecting all ports/VMs they are assigned to immediately_. SCS should make users aware of this as I think this is a very important detail that may not be immediately obvious.
> 
This is a good idea.
>     2. In many paragraphs "Ports" is written with a capital "P", most likely to differentiate Neutron Ports from actual network ports (numbers or NICs). However, in contrast "security groups" is using lower case across the document but also refers to a special concept of OpenStack not identical to the linguistic interpretation of the word combination "security groups".
> 
I wonder, does the documentation already has some internal "standard" for this? Because it is important and I would from now on continue with writing all OpenStack resources with capital letters: Ports, Security Groups, Volumes, Server / VM, Network, etc..
>     3. I'm wondering if we should recommend using security groups as a grouping feature primarily. I.e. not creating individual groups for HTTP, HTTPS, ICMP etc. but actually bringing the "groups" concept into play by suggesting creating abstract service groups, for example:
>        
>        * admin group: ICMP, SSH port
>        * webserver group: HTTP, HTTPS ports
>        * infrastructure group: NTP, DNS ports

I was also thinking about this. But after looking into the default quotas for Security Groups (that is 10 btw) I am a bit afraid that we would recommend to many groups. But maybe we should recommend different ways? Like: 

- you could either use the protocol-based SGs
- or you could user the conceptual SGs

2024-03-22 14:25 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +When talking about network security it does not only rely on firewall rules but also on other configurations or time-crucial allowances.
```suggestion
When implementing network security requirements, firewall rules alone are not always sufficient and might need to be augmented with additional configuration or time-based constraints. Notable examples are:
```

I hope I got the intent of the original sentence right with the rephrasing.

2024-03-22 14:26 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +SSH is needed on many virtual machines to operate its workload.
```suggestion
SSH is needed on many virtual machines to operate their guest operating system.
```

Workloads (as in deployed software and services) often have web UIs and frontends outside of SSH. I think SSH is only relevant for the base system.

2024-03-22 14:27 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +In the Security Group the port 22 can be opened to allow incoming traffic.
```suggestion
In a security group the port 22 can be opened for the TCP protocol to allow incoming SSH connections.
```

2024-03-22 14:30 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +Otherwise default usernames and passwords are used and through the opened port of the Security Group this enables attackers to compromise the virtual machine.
```suggestion
Otherwise default usernames and passwords which are often preconfigured in system images may be exploited through the exposed SSH port which enables attackers to compromise the virtual machine.
```

2024-03-22 14:33 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +But that only should be done with enabling SSH public key authentication (the recommended way) or having a strong username and password policy already applied to the used workload of the VM.
```suggestion
But that only should be done while also restricting the SSH configuration to public key authentication only (the recommended way) or having a strong username and password policy already applied to the operating system of the VM.
```

2024-03-22 14:35 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +It might be usefull to be able to ping a virtual machine or use other ICMP requests.
```suggestion
It might be useful to be able to ping a virtual machine or use other ICMP requests.
```

2024-03-22 14:36 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +But for some workloads this is not or only temporarily needed.
```suggestion
But for some virtual machine configurations this is either not necessary at all or only temporarily needed.
```

2024-03-22 14:37 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +The benefit of Security Groups among other things are to be easily added to and removed from existing virtual machines.
```suggestion
One benefit of security groups among other things is the abiliity to easily added to and removed from existing virtual machines.
```

2024-03-22 14:37 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +So a Security Group allowing ICMP could be added temporarily to a virtual machine for debugging purposes and remoaved from it afterwards.
```suggestion
So a dedicated security group allowing ICMP could be added temporarily to a virtual machine for debugging purposes and removed from it afterwards.
```

2024-03-25 07:01 UTC, josephineSei commented
@markus-hentsch I added your suggestions.
I am not sure right now whether we should keep "security groups" lower case or use capital letters to indicate, that it is an OpenStack resource we are referring.

@artificial-intelligence and @bitkeks could you please look over this guide and state, whether this is security-focused enough? You both indicated, that you wanted to have a more security-focused guide in the DR.

2024-03-25 11:39 UTC, markus-hentsch commented on docs/02-iaas/security-groups.md
> +One benefit of security groups among other things is the abiliity to be easily added to and removed from existing virtual machines.
```suggestion
One benefit of security groups among other things is the ability to be easily added to and removed from existing virtual machines.
```

Sorry my typo.

2024-03-25 11:47 UTC, markus-hentsch approved these changes

2024-04-02 17:15 UTC, berendt approved these changes

2024-04-02 17:15 UTC, berendt commented
Will merge this after final CI run

2024-04-02 17:20 UTC, merged

2024-04-23 07:43 UTC, artificial-intelligence reviewed
I was asked to review this, after it's already merged.
It's mostly looking good to me, some minor nits could be improved, but that should be discussed in a version 2 of this document imho.